### ISSUE TITLE
NN in PyTorch or TensorFlow

### ISSUE THREAD

**Issue by cherepanovic** [misilva73/dtw_som#11]
Hello Maria,

thank you for your provided library.  Might I ask you whether it is planned to extend the lib with PyTorch or Tensorflow tensors? Since training with long time-series is very very time-consuming now and not possible to execute it on GPUs. 

How does the complexity grow caused by the length of timeseries? 

best regards

**Comment by misilva73** [comment]
Hello! Thank you for your interest. However, there are no plans to extend this library to PyTorch or Tensorflow.
