### ISSUE TITLE
AttributeError: 'DtwSom' object has no attribute 'train'

### ISSUE THREAD

**Issue by admir-selimovic** [misilva73/dtw_som#20]
Hi, thanks for the great implementation of SOM!

Evaluation of the following line 

**network.train(sin_dataset, 20)**

results in the following error:

**AttributeError: 'DtwSom' object has no attribute 'train'**

Could you please shed some light on this issue? Thanks!

**Comment by misilva73** [comment]
Can you give more details? How did you install the package and how are you initializing the variable `network`?

**Comment by ClaraGrosse** [comment]
Hi, this looks great!
Unfortunately, however, I am having the same issue as @rimdacivo .
I used a normal pip install and so far have only copied your example code to try and see if it works. so the network initialisation is the same.

Any ideas what this might be down to?

I have also tried uninstalling and reinstalling the package by cloning the repo etc. but with no luck. I get the same issue.

**Comment by misilva73** [comment]
Hi, thanks for raising this. 
Can you try first installing the dependencies with the right versions before installing dtw-som? It could be a breaking change from `pyclustering`.
These are the dependencies:
```bash
dtaidistance==1.2.3
matplotlib==3.1.2
numpy==1.18.1
pyclustering==0.9.3.1
scipy==1.4.1
```

**Comment by ClaraGrosse** [comment]
Thanks for the quick reply! This did actually work! I didn't pay attention to the version before, just the packages. Thank you!
