### ISSUE TITLE
Near to be my favorite work since 1 year of testing unsupervised disaggregation

### ISSUE THREAD

**Issue by Pascal66** [misilva73/dtw_som#33]
![image](https://user-images.githubusercontent.com/3041616/207833847-bcf0570a-c7bf-4f22-806c-56b9eb8ed23a.png)

**Comment by Pascal66** [comment]
Your algo found  3 of 4 reals clusters. Not so easy.
But this one give the pattern associated.
Thank you

**Comment by misilva73** [comment]
What data are you using? I am curious about the use-case.

**Comment by Pascal66** [comment]
Using my energy consumption.
Trying to search patterns by day.
Currently trying [stumpy](https://github.com/TDAmeritrade/stumpy) to see, if it can be better than matrixprofile-ts
